import Link from 'next/link';
import SectionTitle from '../components/SectionTitle';
import ServiceCard from '../components/ServiceCard';
const services=[['◉','Environmental Consultancy','Strategic guidance for a cleaner, compliant and greener environment.'],['▤','Environmental Legal Compliance','Support for statutory and regulatory requirements.'],['▣','MPCB Consent (CTE/CTO)','End-to-end assistance for MPCB consents.'],['💧','CGWA NOC & Ground Water Matters','Consultancy for groundwater approvals and compliance.'],['⚙','STP / ETP / WTP / ZLD Solutions','Design, consultation and implementation support.'],['♧','EIA / EMP & Environment Audit','Impact assessment and audit for sustainable growth.'],['♟','Training & Documentation Support','Capacity building and documentation assistance.']];
export default function Home(){return <main>
<section className="hero"><div className="herooverlay"><div className="heroText"><span className="eyebrow lime">A CLEANER TOMORROW</span><h1>Sustainable Solutions for a <strong>Greener Future</strong></h1><p>Expert environmental consultancy and engineering solutions for a compliant and sustainable tomorrow.</p><div className="actions"><Link className="btn primary" href="/services">Our Services →</Link><Link className="btn outline" href="/contact">Contact Us</Link></div></div><div className="heropills"><span>◌ Environment</span><span>▤ Compliance</span><span>♧ Sustainability</span></div></div></section>
<section className="section"><SectionTitle title="Our Services" text="Comprehensive environmental solutions to help your business stay compliant and sustainable."/><div className="servicesgrid">{services.map(s=><ServiceCard key={s[1]} icon={s[0]} title={s[1]} text={s[2]}/>)}</div></section>
<section className="aboutpreview"><div className="plantvisual"><div><span>TOGETHER</span><b>for a<br/>Sustainable<br/>Tomorrow</b></div></div><div><SectionTitle eyebrow="ABOUT US" title="Committed to a Healthier Environment"/><p>DS VENTRA is an environmental consultancy and engineering solutions company committed to helping industries and organizations achieve regulatory compliance and environmental sustainability. With a practical, solution-focused approach, we support businesses in building a cleaner, safer and greener future.</p><Link className="btn primary small" href="/about">Know More →</Link></div><div className="values"><div><b>◎ Our Mission</b><p>Enable sustainable development through compliance and innovation.</p></div><div><b>◉ Our Vision</b><p>A cleaner, greener and healthier environment for future generations.</p></div><div><b>◇ Our Values</b><p>Integrity | Expertise | Sustainability | Client Focus</p></div></div></section>
<section className="section industries"><SectionTitle title="Industries We Serve" text="We work with diverse industries to ensure compliance and sustainable operations."/><div className="industrygrid">{['Manufacturing','Chemical & Pharma','Infrastructure & Real Estate','Power & Energy','Engineering','Food & Beverage','Healthcare','Commercial Establishments','And More'].map((x,i)=><div key={x}><span>{['▦','⚗','⌂','ϟ','⚙','♜','✚','▥','♧'][i]}</span><p>{x}</p></div>)}</div></section>
<section className="cta"><div><h2>Let’s Build a Cleaner, Greener Tomorrow</h2><p>Partner with DS VENTRA for expert environmental solutions.</p></div><Link className="btn light" href="/contact">Get in Touch →</Link></section>
</main>}
